### ISSUE TITLE
Live Snippets inside dollars delimiter `$$` did not perform well

### ISSUE THREAD

**Issue by K-gihu** [tecosaur/LaTeX-Utilities#82] opened 2019-11-19 11:51 UTC
#### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: **Yes**

### Describe the bug

When I use `$$ $$` and `$ $` as math text delimiters instead of `\[ \]` and `\( \)` and input some text, Live Snippets did not perform. But weirdly, if I input something in `\[\]` beforehand and move cursor into an empty area (which must be below the `\[\]`) surrounded by the dollars sign and input there, live snippet performed normally.

### To Reproduce

Steps to reproduce the behaviour:

1. input `$$$$`.
2. input between dollars sign, like `a1`. Live snippet will not perform.
3. input `\[\]` in next line and input `a1` between them. It will perform well.
4. input `$$$$` in next line and input `a1` between them. It will not perform.
5. delete the `a1` just inputted. move cursor to `\[a_1\]` and do some edit, like delete `1`.
6. move cursor back to `$$$$` and input `a1`. It performed well.
7. but if you do the same thing to the `$$$$` above, it will still not perform.

### Expected behaviour

live snippets inside `$$$$` perform normally.

### Logs

I think the logs are unrelated, but I'll still paste here.

<details>
<summary>LaTeX Workshop Output</summary>

```
[18:44:34] Initializing LaTeX Workshop.
[18:44:35] Creating LaTeX Workshop http and websocket server.
[18:44:35] LaTeX Workshop initialized.
[18:44:35] Server created on 127.0.0.1:4891
[18:44:35] LaTeX Workshop version: 8.4.1
[18:44:35] Snippet data loaded.
```

</details>

<details>
<summary>LaTeX Utilities Output</summary>

```
[18:44:35] Initializing LaTeX Utilities.
[18:44:35] Live Snippets Loaded
[18:44:35] Completion Watcher Initialised
[18:44:35] LaTeX Utilities Started
[18:44:36] TeXCount output: 0+0+0 (0/0/0/2) File: test.tex
[18:44:40] TeXCount output: 0+0+0 (0/0/0/0) File: test.tex
[18:44:43] TeXCount output: 0+0+0 (0/0/0/1) File: test.tex
```
There's still many lines of texcount output below, but I think they are irrelevant.

</details>

<details>
<summary>Developer Tools Console</summary>

None

</details>

### Screenshots

![](https://raw.githubusercontent.com/K-gihu/Images/master/test.gif)

### Desktop

-   OS: Windows 10
-   VS Code version: 1.40.1
-   Extension version: 0.3.4

**Comment by tecosaur** [comment] 2019-11-19 11:55
Hmm. At first glance, this seems like a duplicate of #41, so I'm afraid that this you're not likely to get that functionality.
However, what you describe in step (6) / demonstrate on the 3rd line of the gif is weird behaviour. I'll investigate that.

**Closed** 2019-11-19 16:35 UTC
Labels: bug, duplicate, wontfix
