### ISSUE TITLE
How would one use sympy in snippets?

### ISSUE THREAD

**Issue by ThunderSmotch** [tecosaur/LaTeX-Utilities#43] opened 2019-09-25 19:26 UTC
Assuming that the user has python3 and sympy package installed using the snippets provided by default shouldn't the text `sympy 1+1 sympy` return the replacemente 2 ?

In my case when I run sympy the text gets replaced by "SYMPY_CALCULATING" and then by an empty string, returning nothing.

**Comment by tecosaur** [comment] 2019-09-26 01:02
Huh. Works for me. What do you see in the output panel?

**Comment by ThunderSmotch** [comment] 2019-09-26 07:10
Nothing shows up in the output panel no matter which log I select to view.

**Comment by tecosaur** [comment] 2019-09-26 08:27
How would you feel about debuging?

**Comment by tecosaur** [comment] 2019-09-26 08:55
The issue is probably somewhere in

https://github.com/tecosaur/LaTeX-Utilities/blob/f4387441768cd4d6dcb6ec969738f3181a5f4ba0/src/components/completionWatcher.ts#L340-L387

**Comment by ThunderSmotch** [comment] 2019-09-26 14:20
I'll try to take a look and if I find anything I'll let you know!

**Comment by tecosaur** [comment] 2019-09-30 06:58
Any luck?

**Comment by tecosaur** [comment] 2019-10-07 15:29
@ThunderSmotch \*cough

**Comment by ThunderSmotch** [comment] 2019-10-08 15:07
Hey sorry but so far I haven't been able to figure out where the problem lies, gonna try to compile the python code and run it from cmd to see if that works. I'll post something when I have progress.

**Comment by tecosaur** [comment] 2019-10-28 03:12
@ThunderSmotch I can't reproduce this myself, which means I need your help to solve it :)

**Comment by leoleoasd** [comment] 2022-08-19 03:53
Closing for no action for a long time

**Closed by leoleoasd** 2022-08-19 03:53 UTC
Labels: 🐛 Bug, 🙈 Can't reproduce, ⏳ Waiting for response
