### ISSUE TITLE
LU causes paste shortcut (cmd + v) to break in integrated terminal and search bar

### ISSUE THREAD

**Issue by janosh** [tecosaur/LaTeX-Utilities#64] opened 2019-10-24 11:17 UTC
## Bug Report

With LaTeX Utilities enabled in VS Code 1.39.2 on macOS, <kbd>cmd</kbd> + <kbd>v</kbd> stops working in the integrated terminal and in both the editor and project-wide search bars.

Took me a while to find the culprit but I presume it's due to the shortcut

```json
{
  "key": "cmd+v",
  "command": "latex-utilities.formattedPaste",
  "when": "config.latex-utilities.formattedPaste.useAsDefault && editorTextFocus && editorLangId == 'latex'"
}
```

The issue persists if I disable all extensions except LW & LU.

**Comment by tecosaur** [comment] 2019-10-24 11:48
Hmmm. Thanks for the report. I assumed that when `config.latex-utilities.formattedPaste.useAsDefault` is not set this wouldn't do anything. I guess that isn't the case.

**Comment by tecosaur** [comment] 2019-10-28 03:11
@janosh I think this may be a vscode bug. The `editorTextFocus` condition in `when` should mean it has no effect when you're not in the editor. I assumed but that I had the same issue but didn't notice, but upon testing everything seems to be working as intended for me (I'm on Linux).

**Comment by tecosaur** [comment] 2019-10-29 14:59
Closed via https://github.com/microsoft/vscode/commit/90856c1bdfa6e1ba36c63d9b2bb65d7fef116910

**Closed by tecosaur** 2019-10-29 14:59 UTC
Labels: bug, ∗ vscode
